name: Test Build Docker Image Build (Commit)

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "requirements.txt"
  workflow_dispatch:

permissions:
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }} . .
