name: Build and Publish Docker Image (Tag)
permissions:
  contents: read

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and tag Docker image
        run: |
          # Build once
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }} .

          # Tag for Docker Hub latest
          docker tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:latest

          # Tag for GHCR commit
          docker tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }} \
            ghcr.io/thehsi-hq/pyromanic:${{ github.sha }}

          # Tag for GHCR latest
          docker tag \
            ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }} \
            ghcr.io/thehsi-hq/pyromanic:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/thehsi-hq/pyromanic:${{ github.sha }}
          docker push ghcr.io/thehsi-hq/pyromanic:latest
