name: Build and Publish Docker Image (Commit)

on:
  push:
    branches: [master]
    paths:
      - "Dockerfile"
      - "app.py"
      - "libs/**/*.py"
      - "routes/**/*.py"
      - "requirements.txt"
      - "config/**/*.yaml"
      - "www/**"
      - "assets/**"
  workflow_dispatch:

permissions:
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }}
