name: Test Build Docker Image Build (Commit)

on:
  push:
    branches: [master]
    paths:
      - "Dockerfile"
      - "app.py"
      - "libs/**/*.py"
      - "routes/**/*.py"
      - "requirements.txt"
      - "config/**/*.yaml"
      - "www/**"
      - "assets/**"
  pull_request:
    branches: [master]
    paths:
      - "Dockerfile"
      - "app.py"
      - "libs/**/*.py"
      - "routes/**/*.py"
      - "requirements.txt"
      - "config/**/*.yaml"
      - "www/**"
      - "assets/**"
  workflow_dispatch:

permissions:
  contents: read
jobs:
  build:
    name: Docker Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }} .

      - name: Test Docker Image Startup and Dependencie Installation
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/pyromanic:${{ github.sha }} python -m flask --version
